### ISSUE TITLE
Dockerize it

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/boyarin#110]
- [ ] Boyar runs as a container in the swarm
- [ ] Boyar can upgrade itself

**Comment by netoneko** [comment]
Boyar should not be able to upgrade itself because it violates the decentralization principle and is a gaping security hole.

Also, swarm does not support privileged services. You could run boyar as a container but not in the swarm, it would be different.

**Comment by amir-arad** [comment]
@netoneko please elaborate on the security/centralisation aspects: how is boyar different than the VC process?

**Comment by netoneko** [comment]
@amir-arad first of all, VCs shouldn't be updated automatically either. New versions should go through community approval process that does not exist right now.

There are several key differences between VCs and Boyar:

* VCs do not have access to keys
* VCs are isolated and can't interfere with other VCs
* VCs are unprivileged processes managed from the outside that are subject to resource constraints

None of this applies to Boyar. Boyar is a management tool that provisions VCs, has full access to the cluster and the node keys and configuration.

No changes should happen to the management code unless the node operator applied it themselves (via nebula). Any update applied without consent and knowledge of the node operator is a huge security risk and a liability.
