### ISSUE TITLE
log harvesting mode

### ISSUE THREAD

**Issue by amir-arad** [orbs-network/boyarin#113]
add ability to collect nodes output through stdout and log all of them in a single agent.
consider implementing as separate tool

**Comment by netoneko** [comment]
Node output from stdout is no different from the one that we send to logz.io. Logging to stdout for debugging purposes makes sense, but generally it should be avoided.

**Comment by amir-arad** [comment]
@netoneko could you elaborate why it should be avoided? what are the costs?

**Comment by netoneko** [comment]
Storage is not free. Running out of storage will prevent the services from rescheduling. Adding additional settings to log management for services incurs labor costs.

**Comment by netoneko** [comment]
Closed because of #146
