### ISSUE TITLE
Report Ethereum node version

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/boyarin#116]
Boyar serves a "metrics" page exposing its version number and commit hash.
Add to it the version number and provider (Geth, Parity, etc) of the Ethereum node. This can be achieved using the `web3_clientVersion` Ethereum RPC call, supported by all providers:

 > curl -H "Content-Type: application/json"  -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' eth.orbs.com

`{"jsonrpc":"2.0","result":"Parity-Ethereum//v2.6.6-beta-5162bc2-20191205/x86_64-linux-gnu/rustc1.39.0","id":67}`

**Comment by amir-arad** [comment]
FYI
boyar does not include a web server. it statically configures the proxy to serve the "metrics". 
configuring the proxy is currently implemented as restarting it (killing all connections).

**Comment by electricmonk** [comment]
It's probably time we added a web server, it will be needed also for the IsAlive call

**Comment by netoneko** [comment]
Webserver is a terrible idea because it exposes our critical infrastructure
to a possible attack vector. Please do not add a web server.

**Comment by netoneko** [comment]
Not a concern.
