### ISSUE TITLE
fix and re-instate noisy tests

### ISSUE THREAD

**Issue by amir-arad** [orbs-network/boyarin#117]
the following tests were removed from CI in ##108 and should be fixed:
- [ ] TestE2EAddNewVirtualChainWithSwarmAndBoyar
- [ ] TestE2EWithFullFlowAndDisabledSimilarVchainId
- [ ] TestE2ESingleVchainWithSignerWithSwarmAndBoyar
- [ ] TestE2EWithDockerSwarm
- [ ] TestE2EKeepVolumesBetweenReloadsWithSwarm
- [ ] TestE2EProvisionMultipleVchainsWithSwarmAndBoyar

These tests were removed from CI previously:
 - [ ] Test_UpdateReverseProxyWithSwarm
 - [ ] Test_CreateReverseProxyWithSSL
 - [ ] TestCreateServiceSysctls

**Comment by netoneko** [comment]
Not relevant anymore after #135
